### PR TITLE
LICENSE: init

### LINKED ISSUE #4: Set a license
The repo currently doesn't have a license, but we should set one.

There is currently code from myself, @talyz, and @etu. Do we all agree on licensing our contributions under BSD-3-Clause?

c.f. https://opensource.org/licenses/BSD-3-Clause

### PR DESCRIPTION
**Pull request by lovesegfault**
Closes #4.

Going forward with BSD-3-Clause since no one complained.

@etu @talyz Please review to make sure you're okay with licensing your work under BSD-3.

### CODE REVIEW

**Comment by Mic92** [comment]
BSD3 seems fine. I choose MIT for [NUR](https://github.com/nix-community/NUR) because it is the same license we use for nixpkgs.

**Comment by grahamc** [comment]
Good point. If we wanted to upstream this to NixOS, it would need to be MIT.

**Comment by talyz** [comment]
Maybe we should go with MIT too, then? :)

**Comment by etu** [comment]
MIT is fine as well :)

**Comment by lovesegfault** [comment]
Merging as MIT :)

**Pull request merged**
